[package]
name = "egui-example"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
eframe = "0.28.1"
egui = "0.28.1"
egui-notify = "0.15.0"
egui-phosphor = { version = "0.6.0", features = ["bold", "fill", "light", "thin"] }
strum = "0.26.3"
strum_macros = "0.26.4"
