name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.85
          components: rustfmt, clippy
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Lint
        run: cargo clippy -- -D warnings
